export const projectsData = [
  {
    id: 1,
    title: "To-Do List",
    description: "Description",
    imgUrl: "/images/1.png",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "https://deploy-todo-list.vercel.app/",
  },
  {
    id: 2,
    title: "Blog",
    description: "Description",
    imgUrl: "/images/2.png",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "http://youtube.com",
  },
  {
    id: 3,
    title: "Code",
    description: "Description",
    imgUrl: "/images/3.png",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "/",
  },
  {
    id: 4,
    title: "SEO",
    description: "Description",
    imgUrl: "/images/4.png",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "/",
  },
  {
    id: 5,
    title: "Set-Up Desktop",
    description: "Description",
    imgUrl: "/images/5.png",
    tag: ["All", "Mobile"],
    gitUrl: "/",
    previewUrl: "/",
  },
  {
    id: 6,
    title: "Letter",
    description: "Description",
    imgUrl: "/images/6.png",
    tag: ["All", "Mobile"],
    gitUrl: "/",
    previewUrl: "/",
  },
];
